### ISSUE TITLE
Librem5 / Pinephone / desktop app?

### ISSUE THREAD

**Issue by programmin1** [ev-map/EVMap#210]
This appears to be Java and Android only...? Can we have a GTK+ Linux app so everyone on Librem phone, Pinephone and Linux laptops can use the app please?

Might be a good Hacktoberfest project if you are open to collaboration.

**Comment by johan12345** [comment]
Phew... that's a big project 😅 

So far, EVMap is a native Android app developed in [Kotlin](https://kotlinlang.org/), yes. While I appreciate the idea and am open to collaboration, I'm afraid I wouldn't have the time to be the responsible maintainer for any ports to other platforms (and especially platforms that I don't regularly use myself). So somebody else would need to lead the effort and keep it updated in the future. EVMap on Android already has two independent UIs (on the phone, and for Android Auto/Android Automotive OS on the car screen) that need to be maintained, and there is still a significant [backlog](https://github.com/johan12345/EVMap/issues) of feature requests to be implemented.

If it helps, it should be possible to extract some reusable parts from EVMap's backend code into a pure Kotlin library (e.g., data classes and API clients). But the vast majority of the code depends on the Android SDK, either because it's dealing directly with the UI, or using convenient Android-specific libraries such as [Room](https://developer.android.com/training/data-storage/room) and [ViewModel](https://developer.android.com/topic/libraries/architecture/viewmodel)).

Also, I have no experience so far with GTK+ GUI development using Java/Kotlin - and I imagine the audience (users of non-Android Linux phones that also drive an EV) would not be large enough to really justify the significant effort of porting all the features and making the UI as polished as it is on Android right now?

Laptop users can already easily use the web interfaces of our data sources ([GoingElectric.de](https://www.goingelectric.de/stromtankstellen/), [OpenChargeMap](https://map.openchargemap.io/#/search), [Chargeprice](https://www.chargeprice.app/)) to get most of the relevant features, and the latter even works reasonably well in mobile browsers. I even thought about a web version of EVMap a couple of times, but that's definitely not a concrete plan yet and would probably only have a significantly reduced feature set.

With a quick search I found that it seems to be possible to use Android apps on these phones using [Anbox](https://anbox.io/), have you considered that? If there's something specific about EVMap that's preventing it from running in Anbox there might be ways to address that.

**Comment by johan12345** [comment]
closing as it's not planned from my side
