### ISSUE TITLE
Feature request: open "OpenChargeMap-App" instead of browser for editing of station

### ISSUE THREAD

**Issue by Darulin** [ev-map/EVMap#236]
I love your app, thanks a lot for putting all the effort into it!

Right now, if I click on edit on a station (provided by OCM), it opens the editing page in the browser. Would it be possible to change that/give the option to directly open the editing window inside the OpenChargeMap-App (if it's installed)?

**Comment by johan12345** [comment]
Thank you!

Currently, EVMap links to an URL like `https://openchargemap.org/site/poi/details/203697`. It seems to also be possible to use an URL like `https://map.openchargemap.io/#/poi-editor/203697` to get to the OpenChargeMap web-app in the browser. Would that help?

Opening the actual Android app would require a change on OpenChargeMap's side. The app already listens to links with the `com.webprofusion.openchargemap://` URL scheme, but that only starts the app, it doesn't seem to be possible to pass a link to a specific charger.

**Comment by johan12345** [comment]
After a [recent change](https://github.com/openchargemap/ocm-app/commit/3330c9de96a6db551605a08fe716c59e0fca6a88) at OCM, it is now possible to build links that open the OCM webapp at a specific charger. With b1fd370, EVMap will now use these links, such as https://map.openchargemap.io/?id=92434, instead of the previous https://openchargemap.org/site/poi/details/92434. This provides a nicer experience on mobile devices.

It would now be up to OCM to make their Android app listen to these links instead of opening them in the browser.
