### ISSUE TITLE
Map not moving to my location

### ISSUE THREAD

**Issue by dexic79** [ev-map/EVMap#276]
Hello,
The map is not moving to my location, even if I press the button. It does show my location on the map though, if I move it manually or search for an address.

The map does not move from my home area when I press the location button.

Fairphone 4 with e/OS/ 1.9, location usage is allowed.

Thank you for taking a peek on this matter.

Cheers!

**Comment by johan12345** [comment]
Is this in the F-Droid or Google Play version of the app? And if the latter, are you using Google Maps or OpenStreetMap (Mapbox) as the map provider?

**Comment by celsoazevedo** [comment]
I don't know if it matters, but e/OS uses the [Mozilla Location Service (MLS)](https://location.services.mozilla.com/) for locations (plus satellites, if available), not Google's Location Services that most Android devices have.

If the app was installed via their "app store", then it should the F-Droid version. Apparently they source apps from both F-Droid and Play Store and if an app is available on both, they install the F-Droid version.

**Comment by dexic79** [comment]
Well, other apps do work. Abetterrouteplanner from GPS, OSMAnd from F-Droid, Google Maps is from GPS for sure...

**Comment by analystcmyk** [comment]
Maybe related : after restarting the the fdroid version , it does not remember  the last position and zoom level, it starts with a full global map.

**Comment by dexic79** [comment]
> Is this in the F-Droid or Google Play version of the app? And if the latter, are you using Google Maps or OpenStreetMap (Mapbox) as the map provider?

It is from F-Droid, as far as I know.

**Comment by dexic79** [comment]
Today, the app starts on the city of Fellbach near Stuttgart all the time. And I am in a different place and the GPS pin (the dot on the map) is in the right spot, when I move the map. It just doesn't jump to my place when the app starts nor when I push the button for that. 

I know about this and use addresses or city names for that to find my position, but it is annoying....

**Comment by johan12345** [comment]
I have an idea why this might be: Since Android 12, there is a "fused location provider" integrated in the system, which intelligently combines data from the network and GPS location providers depending on their availability and accuracy (previously this was only possible through Google Play Services APIs, which EVMap avoids to be eligible for F-Droid).

On systems where such a fused provider is available, EVMap previously only listened to location updates from this provider. But it could be that on e/OS the provider exists but does not actually report location updates. So in a5db423 I changed it so that the app still listens to network and GPS updates in case the fused provider does not provide any data.

This will be included in the next update. In case it the issue persists please reopen the issue. I will also add a developer options page which you can enable by tapping the version number in "About" 7 times and then going to "Settings" -> "Developer options". This will then show the current status of all available location providers.
