### ISSUE TITLE
NewMotion real-time info gone?

### ISSUE THREAD

**Issue by gv-sothebys-jeffverk** [ev-map/EVMap#278]
A few weeks (or months?) ago, the realtime charger information from NewMotion just disappeared from the app. Chargers that used to have realtime information working no longer display realtime info, nor any indication that something went wrong with being able to find the information.

Looking at #272, it seems like this is a known issue?

**Comment by johan12345** [comment]
This is not related to #272 - that one is specifically about Tesla chargers, which never had real-time data in EVMap so far as they are not connected to the roaming networks.
For many EU countries I have switched to EnBW as the primary data source as their API is faster, that's why I haven't noticed issues so far. In which country did you see this issue? 

I'm traveling this week, will check afterwards what happened to NewMotion.

**Comment by johan12345** [comment]
Should be fixed with the next release with 9bf7a90. Thanks!
