### ISSUE TITLE
Investigate 3rd party app stores for other vehicle manufacturers

### ISSUE THREAD

**Issue by johan12345** [ev-map/EVMap#281]
To make the Android Automotive OS app available to vehicles without Google services.
- Faurecia Aptoide
- Harman Ignite Store
- ...?

**Comment by johan12345** [comment]
This would require making the Android Auto/Automotive features available in the `foss` variant of the app (i.e. without Google Play Services libraries), i.e. moving the `net.vonforst.evmap.auto` module and related code from the `google` module to the `main` module. In principle this should now be possible, I don't see any hard Google dependencies (except for the Car App Library, which is open source). As a side effect of this, users could then also use the F-Droid version of the app with Android Auto.

**Comment by holdit** [comment]
There's Huawei AppGallery, which is used in China and - I assume - in some of the Chinese cars exported to other countries. Apparently some western brands also use it in China:

https://www.huaweicentral.com/huawei-appgallery-equipped-in-new-bmw-7-series-cars/

If you're looking for places to post the Android app:

- Amazon Appstore: included on their tablets without Google services.
- Aptoide: You may have to use them to submit to "Faurecia Aptoide" anyway, so add the regular app too.
- Huawei AppGallery: Same as the one for cars, I think, and used on all of their devices sold outside China because they can't use Google services.
- Samsung Galaxy Store: included on all their devices, even those with Google services.
- Xiaomi, OPPO, and Vivo also have their stores for Asia, but I don't know how they work.

It's a lot, but if it can be automated, it might be worth doing it.

**Comment by johan12345** [comment]
Thanks! In terms of app stores for phones and tablets it's probably less urgent to add more options, as the Play Store is common in most regions that we support and we already have F-Droid and the APK download from GitHub as an alternative (which is not an option on cars, as APKs cannot easily be sideloaded).
I agree that China is a special case where Play Store and F-Droid are blocked - but if we wanted to adapt EVMap for widespread use in China, distributing through a different app store would by no means be the only problem.

In general, I don't know of an easy way to automate submission to all those app stores (there might be automations for some of them, but I don't know one that can easily be configured for all). It might also require changes to the app (e.g. the F-Droid version of the app currently uses a PayPal link for donations, but other stores may require developers to use their own in-app payment solution, just like the Play Store does).

> https://www.huaweicentral.com/huawei-appgallery-equipped-in-new-bmw-7-series-cars/

AFAIK this only applies to the rear seat entertainment screen, the main infotainment screen of the current BMW 7 series does not run Android. But BMW is partnering with Faurecia Aptoide for future cars.

**Comment by johan12345** [comment]
The AAOS version of EVMap is now submitted to the [Harman Ignite Store](https://car.harman.com/solutions/harman-ignite/store), which may make it available on certain 2023+ vehicles - first partner seems to be [Audi](https://cariad.technology/de/en/news/stories/launch-application-store-for-volkswagen-group.html). It's still pending review by the OEM, if accepted it should appear [here](https://ignitedevelopers.harman.com/apps).

I have also submitted the app to [Faurecia Aptoide](https://faurecia-aptoide.com/), but contrary to what their [documentation] suggests,(https://faurecia-aptoide.com/developers/#app_templates) they don't support template-based Navigation and POI apps on AAOS yet. So, I have submitted the phone version instead, which is not optimal for the car (e.g., it will only be available while parked). It has been accepted, but does not seem to be available in any vehicles so far.
