### ISSUE TITLE
Laggy Map since 1.6.1

### ISSUE THREAD

**Issue by celsoazevedo** [ev-map/EVMap#285]
Since v1.6.1 (I think) I've noticed that the map lags more than before in areas with lots of chargers.

I think EVMap now loads more chargers at once? This is a good thing as before sometimes we'd have to move around or zoom in to load the chargers in a specific area, but the downside is that the map sometimes freezes or lags a lot.

The following video is from the current beta on the Play Store (1.6.3-google), but the same thing happens on 1.6.2 stable. Default settings, clean install, open charge map used as source. Central London is a good position to test as there are lots of lamp post chargers and the map is packed.

https://github.com/ev-map/EVMap/assets/4492221/183c586c-8c0e-41aa-a175-9622eb23a233

I have a OnePlus 8 Pro. Not the fastest phone anymore, but it's powered by a Snapdragon 865 which was used by most flagships from 2020. I assume performance is worse on slower hardware.

**Comment by johan12345** [comment]
seems like the new caching feature (#164) broke support for marker clustering at higher zoom levels for OpenChargeMap. The map can't handle that many markers at once, so we need clustering to make it work. I'll look into it.

**Comment by johan12345** [comment]
sorry, I was wrong. It's not broken due to the caching feature, it's actually loading more chargers. OCM limits the results per page, and in the process of implementing the caching feature, I tried increasing the number of pages that will be loaded. So I guess I need to just allow for clustering at higher zoom levels to make it work.

In contrast to GoingElectric, OCM doesn't support server-side clustering, that's another reason why it may be slower in some cases.

**Comment by johan12345** [comment]
should be improved in the upcoming update 1.6.4

**Comment by celsoazevedo** [comment]
I've tested 1.6.4 from releases and clustering does help. Much better now.

Thanks!
