### ISSUE TITLE
Android Auto: Detected Car does not match any selected

### ISSUE THREAD

**Issue by kscholty** [ev-map/EVMap#289]
My car is a MG4 and I selected this for the price comparison together with a second one.
When I try to compare prices in Android Auto I get informed that the car "Saic Passenger Car SUV" does not match any of the selected cars. Unfortunately this makes it impossible to use the comparison über Android Auto.
It would be great if I could manually select one of the selected cars as it is in the app if it can't be automatically determined.

**Comment by johan12345** [comment]
If you have just one vehicle selected in the app, that one will always be used. The problem is just if you have multiple vehicles selected - then the app needs to try to match the connected car to one of the selected ones. First it tries to match the brand, and if that is still ambiguous it also tries to match the model. In this case, matching the brand already fails, because the car reports "Saic" while Chargeprice expects "MG". I will add a corresponding mapping for this.

Unfortunately, adding a manual selection in case the automatic matching fails is hard to do on Android Auto, because the app can only use a number of predefined UI templates, and the maximum navigation depth is limited as well.
